window["distri/file:master"]({
  "source": {
    "LICENSE": {
      "path": "LICENSE",
      "mode": "100644",
      "content": "The MIT License (MIT)\n\nCopyright (c) 2014 distri\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the \"Software\"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
      "type": "blob"
    },
    "README.md": {
      "path": "README.md",
      "mode": "100644",
      "content": "file\n====\n\nKinda stupid file handling using blobs.\n",
      "type": "blob"
    },
    "main.coffee.md": {
      "path": "main.coffee.md",
      "mode": "100644",
      "content": "File\n====\n\nStore files in blobs. Get files from Base64 encoded data via Github or anything\nelse that we can cram into blobs.\n\nMethods are async and return promises.\n\nObservables may be involved.\n\n    module.exports = (I={}, self={}) ->\n      \n    \n      return self\n",
      "type": "blob"
    }
  },
  "distribution": {
    "main": {
      "path": "main",
      "content": "(function() {\n  module.exports = function(I, self) {\n    if (I == null) {\n      I = {};\n    }\n    if (self == null) {\n      self = {};\n    }\n    return self;\n  };\n\n}).call(this);\n\n//# sourceURL=main.coffee",
      "type": "blob"
    }
  },
  "progenitor": {
    "url": "http://strd6.github.io/editor/"
  },
  "entryPoint": "main",
  "repository": {
    "id": 16927976,
    "name": "file",
    "full_name": "distri/file",
    "owner": {
      "login": "distri",
      "id": 6005125,
      "avatar_url": "https://identicons.github.com/f90c81ffc1498e260c820082f2e7ca5f.png",
      "gravatar_id": null,
      "url": "https://api.github.com/users/distri",
      "html_url": "https://github.com/distri",
      "followers_url": "https://api.github.com/users/distri/followers",
      "following_url": "https://api.github.com/users/distri/following{/other_user}",
      "gists_url": "https://api.github.com/users/distri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/distri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/distri/subscriptions",
      "organizations_url": "https://api.github.com/users/distri/orgs",
      "repos_url": "https://api.github.com/users/distri/repos",
      "events_url": "https://api.github.com/users/distri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/distri/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/distri/file",
    "description": "Kinda stupid file handling using blobs.",
    "fork": false,
    "url": "https://api.github.com/repos/distri/file",
    "forks_url": "https://api.github.com/repos/distri/file/forks",
    "keys_url": "https://api.github.com/repos/distri/file/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/distri/file/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/distri/file/teams",
    "hooks_url": "https://api.github.com/repos/distri/file/hooks",
    "issue_events_url": "https://api.github.com/repos/distri/file/issues/events{/number}",
    "events_url": "https://api.github.com/repos/distri/file/events",
    "assignees_url": "https://api.github.com/repos/distri/file/assignees{/user}",
    "branches_url": "https://api.github.com/repos/distri/file/branches{/branch}",
    "tags_url": "https://api.github.com/repos/distri/file/tags",
    "blobs_url": "https://api.github.com/repos/distri/file/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/distri/file/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/distri/file/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/distri/file/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/distri/file/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/distri/file/languages",
    "stargazers_url": "https://api.github.com/repos/distri/file/stargazers",
    "contributors_url": "https://api.github.com/repos/distri/file/contributors",
    "subscribers_url": "https://api.github.com/repos/distri/file/subscribers",
    "subscription_url": "https://api.github.com/repos/distri/file/subscription",
    "commits_url": "https://api.github.com/repos/distri/file/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/distri/file/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/distri/file/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/distri/file/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/distri/file/contents/{+path}",
    "compare_url": "https://api.github.com/repos/distri/file/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/distri/file/merges",
    "archive_url": "https://api.github.com/repos/distri/file/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/distri/file/downloads",
    "issues_url": "https://api.github.com/repos/distri/file/issues{/number}",
    "pulls_url": "https://api.github.com/repos/distri/file/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/distri/file/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/distri/file/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/distri/file/labels{/name}",
    "releases_url": "https://api.github.com/repos/distri/file/releases{/id}",
    "created_at": "2014-02-17T21:59:32Z",
    "updated_at": "2014-02-17T21:59:32Z",
    "pushed_at": "2014-02-17T21:59:32Z",
    "git_url": "git://github.com/distri/file.git",
    "ssh_url": "git@github.com:distri/file.git",
    "clone_url": "https://github.com/distri/file.git",
    "svn_url": "https://github.com/distri/file",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "master_branch": "master",
    "permissions": {
      "admin": true,
      "push": true,
      "pull": true
    },
    "organization": {
      "login": "distri",
      "id": 6005125,
      "avatar_url": "https://identicons.github.com/f90c81ffc1498e260c820082f2e7ca5f.png",
      "gravatar_id": null,
      "url": "https://api.github.com/users/distri",
      "html_url": "https://github.com/distri",
      "followers_url": "https://api.github.com/users/distri/followers",
      "following_url": "https://api.github.com/users/distri/following{/other_user}",
      "gists_url": "https://api.github.com/users/distri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/distri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/distri/subscriptions",
      "organizations_url": "https://api.github.com/users/distri/orgs",
      "repos_url": "https://api.github.com/users/distri/repos",
      "events_url": "https://api.github.com/users/distri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/distri/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "network_count": 0,
    "subscribers_count": 2,
    "branch": "master",
    "defaultBranch": "master"
  },
  "dependencies": {}
});